controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
#Custom
user_controller:
    resource: ../../src/Component/User/Communication/
    type: annotation

#For test
app_token:
    resource: ../../src/TestController/
    type: annotation