controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
#Custom
user_controller:
    resource: ../../src/Component/User/Communication/
    type: annotation

exam_controller:
    resource: ../../src/Component/Exam/Communication/
    type: annotation

question_controller:
    resource: ../../src/Component/Question/Communication/
    type: annotation

userQuestion_controller:
    resource: ../../src/Component/UserQuestion/Communication/
    type: annotation

#For test
app_token:
    resource: ../../src/TestController/
    type: annotation