name: testing
on:
  push:
    branches: [ client ]
  pull_request:
    branches: [ client ]
jobs:
  cs-fixer:
    name: cs-fixer
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v1

      - name: composer install
        run: composer install

      - name: run cs-fixer
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src
  phpStanPsalm:
    name: phpStan & Psalm test
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v1

      - name: composer install
        run: composer install

      - name: run phpStan
        run: vendor/bin/phpstan analyse -c phpStan.neon

      - name: run Psalm
        run: vendor/bin/psalm
  Test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v1

      - name: composer install
        run: composer install

      - name: start docker
        run: docker-compose up -d

      - name: start server on port 8001
        run: php bin/console serve -d --port=8001

      - name: show docker containers
        run: docker ps -a

      - name: Wait for MySQL
        run: sleep 10

      - name: create database
        run: php bin/console --env=test doctrine:database:create

      - name: migrate
        run: php bin/console --env=test doctrine:migrations:migrate --no-interaction

      - name: run phpunit
        run: php vendor/bin/phpunit

      - name: run infection
        run: php vendor/bin/infection

      - name: stop server
        if: always()
        run: php bin/console server:stop

      - name: Stop docker
        if: always()
        run: docker-compose down